### ISSUE TITLE
Support moving simple cell to different location

### ISSUE THREAD

**Issue by shulhi** [plow-technologies/simple-cell#19]
This is somewhat related to plow-technologies/hmi-server#69

When we moved the store to a different server, the `last.touch` file contains the path of the last file modified. The problem is, the path is hard coded as absolute path i.e. `/home/node1/hmi-server/store`, and when we moved to a different server which has a different setup i.e. `/home/node30/hmi-server`, the store no longer works because it expects a different path.

I think it would be nice if we could support relative path - relative to the binary, this would make it easy to transfer store between servers. For example, 

`hmi-server` binary is run at `/home/node1/hmi-server` and `last.touch` contains relative path `store`, and simple-cell would go look at `/home/node1/hmi-server/store`.

Or maybe it can support both, when path starts with `/`, it should be considered as absolute path.

**Comment by smurphy8** [comment]
Maybe a better way is to leave the paths absolute and write export and import store

**Comment by smurphy8** [comment]
@shulhi is the last.touch file the only part that broke?

**Comment by shulhi** [comment]
@smurphy8 yeah. The absolute path also caused issue in feature-flag tests because I have integration tests that simulate erroneous flags after reading it from the store.  The absolute path causes the store not to be found. I somewhat fixed the tests by running `sed` to change the path to `PWD` before running the tests.

**Comment by smurphy8** [comment]
@cotrone this would be a good one to focus on I think

**Comment by smurphy8** [comment]
@cotrone did you complete this?

**Comment by cotrone** [comment]
Ah, yeah. I will PR this today

**Comment by smurphy8** [comment]
k great, please link PR and close this when it is merged @cotrone
